// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://autdiptxejoatfoqzyfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dGRpcHR4ZWpvYXRmb3F6eWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTI1MzQsImV4cCI6MjA2MDIyODUzNH0.q7-dil-0lVwFraLW2L_vwysI3bw3Cib9_3PUS-J3PaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);